CSRCS += $(LVGL_DIR)/src/lv_widgets/lv_arc.c
CSRCS += $(LVGL_DIR)/src/lv_widgets/lv_bar.c
CSRCS += $(LVGL_DIR)/src/lv_widgets/lv_checkbox.c
CSRCS += $(LVGL_DIR)/src/lv_widgets/lv_cpicker.c
CSRCS += $(LVGL_DIR)/src/lv_widgets/lv_dropdown.c
CSRCS += $(LVGL_DIR)/src/lv_widgets/lv_keyboard.c
CSRCS += $(LVGL_DIR)/src/lv_widgets/lv_line.c
CSRCS += $(LVGL_DIR)/src/lv_widgets/lv_msgbox.c
CSRCS += $(LVGL_DIR)/src/lv_widgets/lv_spinner.c
CSRCS += $(LVGL_DIR)/src/lv_widgets/lv_roller.c
CSRCS += $(LVGL_DIR)/src/lv_widgets/lv_table.c
CSRCS += $(LVGL_DIR)/src/lv_widgets/lv_tabview.c
CSRCS += $(LVGL_DIR)/src/lv_widgets/lv_tileview.c
CSRCS += $(LVGL_DIR)/src/lv_widgets/lv_btn.c
CSRCS += $(LVGL_DIR)/src/lv_widgets/lv_calendar.c
CSRCS += $(LVGL_DIR)/src/lv_widgets/lv_chart.c
CSRCS += $(LVGL_DIR)/src/lv_widgets/lv_canvas.c
CSRCS += $(LVGL_DIR)/src/lv_widgets/lv_gauge.c
CSRCS += $(LVGL_DIR)/src/lv_widgets/lv_label.c
CSRCS += $(LVGL_DIR)/src/lv_widgets/lv_list.c
CSRCS += $(LVGL_DIR)/src/lv_widgets/lv_slider.c
CSRCS += $(LVGL_DIR)/src/lv_widgets/lv_textarea.c
CSRCS += $(LVGL_DIR)/src/lv_widgets/lv_spinbox.c
CSRCS += $(LVGL_DIR)/src/lv_widgets/lv_btnmatrix.c
CSRCS += $(LVGL_DIR)/src/lv_widgets/lv_cont.c
CSRCS += $(LVGL_DIR)/src/lv_widgets/lv_img.c
CSRCS += $(LVGL_DIR)/src/lv_widgets/lv_imgbtn.c
CSRCS += $(LVGL_DIR)/src/lv_widgets/lv_led.c
CSRCS += $(LVGL_DIR)/src/lv_widgets/lv_linemeter.c
CSRCS += $(LVGL_DIR)/src/lv_widgets/lv_page.c
CSRCS += $(LVGL_DIR)/src/lv_widgets/lv_switch.c
CSRCS += $(LVGL_DIR)/src/lv_widgets/lv_win.c
CSRCS += $(LVGL_DIR)/src/lv_widgets/lv_objmask.c

DEPPATH += --dep-path $(LVGL_DIR)/src/lv_widgets
VPATH += $(LVGL_DIR)/src/lv_widgets

CFLAGS += "-I$(LVGL_DIR)/src/lv_widgets"
